version: '3.3'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: app-veterinario:latest
#    depends_on:
#      - db
#    ports:
#    - "443:8443"
#    - "80:8080"
#    networks:
#      - app-veterinario

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ediaristas'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ediaristas-db:/var/lib/mysql
    networks:
      - ediaristas

volumes:
  ediaristas-db:

networks:
  ediaristas:
    driver: bridge
